# Generated by Django 4.2.2 on 2023-07-03 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='frequency_penalty',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(2.0), django.core.validators.MinValueValidator(-2.0)]),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='max_tokens',
            field=models.IntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='presence_penalty',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(2.0), django.core.validators.MinValueValidator(-2.0)]),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='temperature',
            field=models.FloatField(default=0.5, validators=[django.core.validators.MaxValueValidator(1.0), django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='attached_message_count',
            field=models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)]),
        ),
    ]
