# Generated by Django 4.2.2 on 2023-07-25 10:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_message_use_model_alter_message_flag_qcmd"),
    ]

    operations = [
        migrations.AddField(
            model_name="userpreference",
            name="with_qcmd",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="timestamp",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="max_tokens",
            field=models.IntegerField(
                default=1000,
                validators=[
                    django.core.validators.MaxValueValidator(2000),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="temperature",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(1.0),
                    django.core.validators.MinValueValidator(0.0),
                ],
            ),
        ),
    ]
